<?php
/**
 * PDMS Segments Model
 *
 * Data interface for PDMS Segments.
 *
 * @package PDMS\Splitter\Models
 */

namespace PDMS\Splitter\Models;

/**
 * PDMS Segments Model class.
 */
class SegmentsModel {
	/**
	 * Get segmented menu locations.
	 *
	 * @param string $output The output type.
	 *
	 * @return array
	 */
	public static function get_segments( $output = ARRAY_A ) {
		// Get the current locations option.
		$segments = get_option( PDMS_META_KEY, array() );

		// Ensure segments is an array.
		$segments = ( is_array( $segments ) ) ? $segments : array();

		// Add name and slug to the segment.
		foreach ( $segments as $slug => $segment ) {
			$segments[ $slug ]['name'] = self::get_registered_nav_menus_filtered()[ $slug ];
			$segments[ $slug ]['slug'] = $slug;
		}

		// Return the segments based on the output type.
		switch ( $output ) {
			case ARRAY_N:
				return array_values( $segments );

			case ARRAY_A:
			default:
				return $segments;
		}
	}

	/**
	 * Update segmented menu locations.
	 *
	 * @param array $segments The segments value to update.
	 *
	 * @return bool
	 */
	public static function update_segments( $segments ) {
		// Remove name and slug from the segment.
		foreach ( $segments as $slug => $segment ) {
			unset( $segments[ $slug ]['name'] );
			unset( $segments[ $slug ]['slug'] );
		}

		// Update segments and return the results.
		return update_option( PDMS_META_KEY, $segments, true );
	}

	/**
	 * Get a filtered array of registered nav menus.
	 *
	 * @return array
	 */
	public static function get_registered_nav_menus_filtered() {
		$locations = get_registered_nav_menus();

		// Filter out locations generated by PDMS.
		foreach ( $locations as $slug => $name ) {
			if ( false !== strpos( $slug, '-' . PDMS_PREFIX . '-' ) ) {
				unset( $locations[ $slug ] );
			}
		}

		return $locations;
	}

	/**
	 * Get the active segment by slug.
	 *
	 * @return array|null
	 */
	public static function maybe_get_active_segment_by_slug() {
		$action = ( isset( $_GET['action'] ) ) ? sanitize_text_field( wp_unslash( $_GET['action'] ) ) : null;
		$slug   = ( isset( $_GET['slug'] ) ) ? sanitize_text_field( wp_unslash( $_GET['slug'] ) ) : null;
		$nonce  = ( isset( $_GET[ PDMS_PREFIX . '_nonce' ] ) ) ? sanitize_text_field( wp_unslash( $_GET[ PDMS_PREFIX . '_nonce' ] ) ) : null;

		// Exit early condition.
		if ( empty( $nonce ) || ! wp_verify_nonce( $nonce, PDMS_PREFIX . '_secure_edit_' . $slug ) ) {
			return;
		}

		// Exit early condition.
		if ( ! $slug || 'edit' !== $action ) {
			return;
		}

		$segments = self::get_segments();

		if ( isset( $segments[ $slug ] ) ) {
			return $segments[ $slug ];
		}
	}
}
